AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  java-daily-cleanup-job

  SAM Template for java-daily-cleanup-job

Globals:
  Function:
    Environment:
      Variables:
        BUCKET_NAME: daily-cleanup-bucket
        DAYS: "30"
        SNS_TOPIC_ARN: !Ref DailyCleanupSNSTopic
        DRY_RUN: "false"
        FILE_TYPES: ".log,.tmp,.bak"
        PREFIXES: "logs/,temp/,backup/"
        CLEANUP_SCHEDULE: "0 0 * * ? *"  # Default: midnight UTC, but can be overridden

Parameters:
  CleanupSchedule:
    Type: String
    Default: "cron(0 0 * * ? *)"
    Description: "Cron expression for cleanup schedule (default: daily at midnight UTC)"
    AllowedPattern: "cron\\([0-9*/, -?]+\\)"

Resources:
  DailyCleanupSNSTopic:
    Type: AWS::SNS::Topic
  DailyCleanUpFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: DailyCleanupFunction
      Handler: msjackiebrown.DailyCleanupHandler::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      MemorySize: 512
      Role: !GetAtt DailyCleanupFunctionRole.Arn
      Environment:
        Variables:
          CLEANUP_SCHEDULE: !Ref CleanupSchedule
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: !Ref CleanupSchedule
            Name: DailyCleanup
            Description: "Triggers the cleanup Lambda function based on configured schedule"
  DailyCleanupFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:DeleteObject
                  - s3:ListBucket
                  - s3:GetObject
                Resource:
                  - arn:aws:s3:::daily-cleanup-bucket
                  - arn:aws:s3:::daily-cleanup-bucket/*
        - PolicyName: LambdaBasicExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
        - PolicyName: SNSAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: "*"
        - PolicyName: CloudWatchMetricsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                Resource: "*"

